name: 28581 Deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
on:
  workflow_run:
    workflows: ["28581 Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Python environement ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to DockerHub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/obdelava_slike:${{ matrix.python-version }} .

      - name: Push to DockerHUb
        run: docker push $DOCKER_USERNAME/obdelava_slike:${{ matrix.python-version }}